### ISSUE TITLE
Build fails on 32 bit architectures

### ISSUE THREAD

**Issue by mark2b** [tinyzimmer/go-glib#4]
Hi 
Trying build for RPI GOOS=linux GOARCH=arm CGO_ENABLED=1
get build failure
```
# github.com/tinyzimmer/go-glib/glib
vendor/github.com/tinyzimmer/go-glib/glib/gobject.go:247:22: type [1073741824]int larger than address space
vendor/github.com/tinyzimmer/go-glib/glib/gobject.go:247:22: type [1073741824]int too large
vendor/github.com/tinyzimmer/go-glib/glib/gobjectclass.go:49:25: type [1073741824]*_Ctype_struct__GParamSpec larger than address space
vendor/github.com/tinyzimmer/go-glib/glib/gobjectclass.go:49:25: type [1073741824]*_Ctype_struct__GParamSpec too large
vendor/github.com/tinyzimmer/go-glib/glib/gparamspec.go:74:27: type [1073741824]_Ctype_struct__GFlagsValue larger than address space
vendor/github.com/tinyzimmer/go-glib/glib/gparamspec.go:74:27: type [1073741824]_Ctype_struct__GFlagsValue too large

```

**Comment by atishnazir** [comment]
Just looking at this because curious (and just raised a PR in one of those files).  Those error messages don't quite correspond to code in my workspace.  Could you post which version of go-glib you're using?

How are you performing the compilation, is this on a RaspberryPi or are you cross compiling (how are you dealing with CGO cross compile dependencies such as toolchain and gstreamer)?

**Comment by mark2b** [comment]
Hi, 
Actually I compile go-gst, which depends from go-glib
```
github.com/tinyzimmer/go-glib v0.0.24
github.com/tinyzimmer/go-gst v0.2.30
```
I compile it in docker with toolchain and gstreamer (armhf)  installed 
`CGO_LDFLAGS=-Wl,-rpath-link,/lib/arm-linux-gnueabihf:/usr/lib/arm-linux-gnueabihf PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig CC=/opt/cross-pi-gcc/bin/arm-linux-gnueabihf-gcc CXX=/opt/cross-pi-gcc/bin/arm-linux-gnueabihf-g++ GOOS=linux GOARCH=arm GOPATH=/workspace/go CGO_ENABLED=1`

previously I used  github.com/notedit/gst and compilation worked 
but because memory leaks in the notedit/gst decided to try go-gst

**Comment by atishnazir** [comment]
Any chance you could a cut down verison of your Dockerfile?

**Comment by mark2b** [comment]
Docker for build
`
FROM mark2b/golang-rpi-toolchain:1.16.6

VOLUME /workspace
WORKDIR /workspace

RUN dpkg --add-architecture armhf
RUN apt-get update

RUN apt-get -y install libgstreamer1.0-dev:armhf libgstreamer-plugins-base1.0-dev:armhf \
      gstreamer1.0-plugins-base:armhf gstreamer1.0-plugins-good:armhf \
      gstreamer1.0-plugins-bad:armhf gstreamer1.0-plugins-ugly:armhf \
      gstreamer1.0-libav:armhf libgstrtspserver-1.0-dev:armhf

ENTRYPOINT ["/bin/sh", "-c"]
`

Parent docker with toolchain

`
FROM golang:1.16.6

ADD raspi-toolchain.tar.gz /opt
`
